version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "bazaartrade-mysql-1:3306", "0", "java", "-jar", "demo-1.0-SNAPSHOT.jar"]
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "@MDP2023password"
      MYSQL_DATABASE: "BazaarTrade"
      MYSQL_USER: "Achille"
      MYSQL_PASSWORD: "@MDP2023achille"
    ports:
      - "3306:3306"
    networks:
      - app-network

  keycloak:
    image: jboss/keycloak
    ports:
      - "8081:8080"
networks:
  app-network:
    driver: bridge